src/config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from core.routers import urlpatterns as core_api_urls
from core.views import ListAllItems
from user.routers import urlpatterns as user_api_urls
from core.urls import urlpatterns as core_urls 
from user import urls as user_urls

api_urls = core_api_urls + user_api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include(api_urls)),
    path("", include(core_urls)),
    path(
        "", include((user_urls, "auth"), namespace="auth")
    ),
    path(
        "",
        ListAllItems.as_view(),
        name="site_root"
    ),
]

src/core/urls.py
from django.urls import path
from django.urls.base import reverse_lazy

from .views import(
    # CompanyDetail,
    # CompanyList,
    # CompanyCreate,
    # CompanyDelete,
    # CompanyUpdate,
    ItemDetail,
    ItemList,
    ItemCreate,
    ItemDelete,
    ItemUpdate,
    MoveItemToCart,
    CartDetail,
)

urlpatterns = [
    # path("company/", CompanyList.as_view(), name="company_list"),
    # path(
    #     "company/create/",
    #     CompanyCreate.as_view(),
    #     name="company_create"
    # ),
    # path(
    #     "company/<str:slug>/",
    #     CompanyDetail.as_view(),
    #     name="company_detail"
    # ),
    # path(
    #     "company/<str:slug>/update/",
    #     CompanyUpdate.as_view(),
    #     name="company_update"
    # ),
    # path(
    #     "company/<str:slug>/delete/",
    #     CompanyDelete.as_view(),
    #     name="company_delete"
    # ),
    path("item/", ItemList.as_view(), name="item_list"),
    path(
        "item/create/",
        ItemCreate.as_view(),
        name="item_create"
    ),
    path(
        "item/<str:slug>/",
        ItemDetail.as_view(),
        name="item_detail"
    ),
    path(
        "item/<str:slug>/update/",
        ItemUpdate.as_view(),
        name="item_update"
    ),
    path(
        "item/<str:slug>/delete/",
        ItemDelete.as_view(),
        name="item_delete"
    ),
    path("cart/", CartDetail.as_view(), name="cart"),
    path(
        "item/<str:slug>/move_to_cart/",
        MoveItemToCart.as_view(success_url=reverse_lazy("cart")),
        name="move_item_to_cart"
    ),
]

src/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse_lazy
from django.views.generic import TemplateView
from django_registration.backends.activation.views import (
    RegistrationView,
)

from .forms import CompanyRegistrationForm, RegistrationForm
from .views import (
    AccountPage,
    ActivationView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
    CompanyApprovalPendingList,
    CompanyApproveView,
    UserList,
)

urlpatterns = [
    path("account/", AccountPage.as_view(), name="account"),
    path(
        "login/",
        LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(
            template_name="user/logout.html"
        ),
        name="logout",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^activate/(?P<activation_key>[-:\w]+)/$",
        ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "register/",
        RegistrationView.as_view(
            form_class=RegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_complete"
            ),
        ),
        name="django_registration_register",
    ),
    path(
        "register/complete/",
        TemplateView.as_view(
            template_name="django_registration/registration_complete.html"
        ),
        name="django_registration_complete",
    ),
    path(
        "register/closed/",
        TemplateView.as_view(
            template_name="django_registration/registration_closed.html"
        ),
        name="django_registration_disallowed",
    ),
    path(
        "register_company/",
        RegistrationView.as_view(
            form_class=CompanyRegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_company_complete"
            ),
        ),
        name="django_registration_register_company",
    ),
    path(
        "register_company/complete/",
        TemplateView.as_view(
            template_name="django_registration/company_registration_complete.html"
        ),
        name="django_registration_company_complete",
    ),
    path(
        "companies_pending_approval/",
        CompanyApprovalPendingList.as_view(),
        name="django_approval_pending_companies",
    ),
    path(
        "approve_company/<int:pk>/",
        CompanyApproveView.as_view(),
        name="django_approve_company",
    ),
    path(
        "user/",
        UserList.as_view(),
        name="django_list_users"
    )
]

src/user/models.py
import uuid
from django.db.models.deletion import CASCADE
from django.urls import reverse
from improved_user.model_mixins import AbstractUser
from django.db import models
from django_extensions.db.fields import AutoSlugField

class User(AbstractUser):

    type = models.CharField(
        max_length=20,
        default="buyer"
    )
    verified = models.BooleanField(default=True)
    uid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
    )

    def __str__(self):
        return f"email: {self.email}, type: {self.type}"

    def get_absolute_url(self):
        return reverse(
            "auth:django_approve_company",
            kwargs={
                "pk": self.pk
            }
        )


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    short_name = models.CharField(max_length=20)
    slug = AutoSlugField(
        max_length=90,
        populate_from=["user__uid","short_name"]
    )
    line_1 = models.CharField(max_length=32)
    line_2 = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=32)
    pincode = models.IntegerField()
    country = models.CharField(max_length=32)

src/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django_registration.validators import (
    DUPLICATE_EMAIL,
    CaseInsensitiveUnique,
    validate_confusables_email,
)
from django.forms import ModelForm
User = get_user_model()


class RegistrationForm(UserCreationForm):
    """Form for registering a new user account.

    Validates that the requested email is not already in use, and
    requires the password to be entered twice to catch typos.
    """

    class Meta:
        model = User
        fields = [
            User.USERNAME_FIELD,
            "password1",
            "password2",
            "full_name",
            "short_name",
        ]
        field_classes = {}

    error_css_class = "error"
    required_css_class = "required"

    def __init__(self, *args, **kwargs):
        """Configure username/email field to be validated"""
        super().__init__(*args, **kwargs)
        self.fields[User.USERNAME_FIELD].validators.extend(
            [
                validate_confusables_email,
                CaseInsensitiveUnique(
                    User,
                    User.USERNAME_FIELD,
                    DUPLICATE_EMAIL,
                ),
            ]
        )

class CompanyRegistrationForm(UserCreationForm):
    """Form for registering a new company account.

    Validates that the requested email is not already in use, and
    requires the password to be entered twice to catch typos.
    """

    class Meta:
        model = User
        fields = [
            User.USERNAME_FIELD,
            "password1",
            "password2",
            "full_name",
            "short_name",
        ]
        field_classes = {}

    error_css_class = "error"
    required_css_class = "required"

    def __init__(self, *args, **kwargs):
        """Configure username/email field to be validated"""
        super().__init__(*args, **kwargs)
        self.fields[User.USERNAME_FIELD].validators.extend(
            [
                validate_confusables_email,
                CaseInsensitiveUnique(
                    User,
                    User.USERNAME_FIELD,
                    DUPLICATE_EMAIL,
                ),
            ]
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.type = "company"
        user.verified = False
        if commit:
            user.save()
        return user


class CompanyApproveForm(ModelForm):
    
    class Meta:
        model = User
        fields = ["verified"]
    

src/user/views.py
"""Views for User app"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    PasswordChangeView as BasePasswordChangeView,
    PasswordResetConfirmView as BasePasswordResetConfirmView,
    PasswordResetView as BasePasswordResetView,
)
from django.contrib.messages import success
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, UpdateView
from django_registration.backends.activation.views import (
    ActivationView as BaseActivationView,
)
from django_registration.exceptions import ActivationError

from .forms import CompanyApproveForm
from .models import User
from django.utils.translation import gettext_lazy as _

from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView
)
from .serializers import(
    CompanySerializer,
    BuyerSerializer,
)

from functools import reduce
from operator import or_
from .utils import get_perms
from django.contrib.auth.models import Permission



class AccountPage(LoginRequiredMixin, TemplateView):
    """Display page with links to manage account

    For instance, link to page to change password.
    """

    template_name = "user/account.html"


class ActivationView(BaseActivationView):
    """Notify user of activation and direct to login"""

    success_url = reverse_lazy("auth:login")
    NOT_VERIFIED_MESSAGE = _("The account has not been verfied by our administrators.")

    # def activate(self, *args, **kwargs):
    #     """Notify user after activating successfully

    #     https://github.com/ubernostrum/django-registration/blob/58be01f5858a/src/django_registration/backends/activation/views.py#L129
    #     """
    #     user = super().activate(*args, **kwargs)
    #     success(
    #         self.request,
    #         "Your account has been activated."
    #         " You may now sign-in.",
    #         fail_silently=True,
    #     )
    #     return user

    def activate(self, *args, **kwargs):
        username = self.validate_key(kwargs.get("activation_key"))
        user = self.get_user(username)
        if user.verified:
            user.is_active = True
            # add permissions if the user is company
            if user.type == 'company':
                user.user_permissions.add(
                    *list(
                        Permission.objects.filter(
                            reduce(
                                or_,
                                (
                                    get_perms(perms)
                                    for perms in [
                                        "core.add_item",
                                        "core.change_item",
                                        "core.delete_item",
                                        "core.view_item",
                                    ]
                                )
                            )
                        )
                    )
                )
            user.save()
            success(
                self.request,
                "Your account has been activated."
                " You may now sign-in.",
                fail_silently=True,  
            )
            return user
        else:
            raise ActivationError(
                self.NOT_VERIFIED_MESSAGE, code="not_verified"
            )


class SuccessMessageMixin:
    """Notify user of success after submitting a form"""

    success_message = "Success!"

    def form_valid(self, form):
        """When form is valid: notify user of success"""
        success(
            self.request,
            self.success_message,
            fail_silently=True,
        )
        return super().form_valid(form)


class PasswordChangeView(
    SuccessMessageMixin, BasePasswordChangeView
):
    """Allow authenticated users to change password;

    Messages success to user
    """

    success_message = "Password Changed Successfully"
    success_url = reverse_lazy("auth:account")
    template_name = "user/password_change_form.html"


class PasswordResetView(
    SuccessMessageMixin, BasePasswordResetView
):
    """Allow anonymous users to reset password;

    Messages success to user
    """

    email_template_name = "user/password_reset_email.txt"
    subject_template_name = (
        "user/password_reset_subject.txt"
    )
    success_message = (
        "Password email sent: please check your email"
    )
    success_url = reverse_lazy("auth:login")
    template_name = "user/password_reset_form.html"


class PasswordResetConfirmView(
    SuccessMessageMixin, BasePasswordResetConfirmView
):
    """Prompt user for a new password"""

    success_message = "Password reset: Please login with your new password."
    success_url = reverse_lazy("auth:login")
    template_name = "user/password_reset_confirm.html"

class CompanyApprovalPendingList(ListView):

    queryset = User.objects.all().filter(verified=False)
    template_name = 'user/company_pending_approval.html'

class CompanyApproveView(UpdateView):
    
    success_url = reverse_lazy("auth:django_approval_pending_companies")
    form_class = CompanyApproveForm
    queryset = User.objects.all()
    template_name = "user/approve_company.html"


class UserList(ListView):
    queryset = User.objects.all()
    template_name = 'user/list.html'


# API views
class CompanyApiDetail(RetrieveAPIView):
    queryset = User.objects.all().filter(type='company', is_staff=False)
    serializer_class = CompanySerializer
    lookup_field = "uid"

class CompanyApiList(ListAPIView):

    queryset = User.objects.all().filter(type='company', is_staff=False)
    serializer_class = CompanySerializer


class BuyerApiDetail(RetrieveAPIView):
    queryset = User.objects.all().filter(type='buyer', is_staff=False)
    serializer_class = CompanySerializer
    lookup_field = "uid"

class BuyerApiList(ListAPIView):

    queryset = User.objects.all().filter(type='buyer', is_staff=False)
    serializer_class = CompanySerializer

src/templates/user/account.html
{% extends parent_template|default:"user/base.html" %}

{% block content %}
  <h2>{{ user.full_name }}</h2>
  <a href="{%  url 'auth:password_change' %}">
    Change your password
  </a>
{% endblock %}

src/templates/user/approve_company.html
{% extends parent_template|default:"user/base.html" %}

{% block title %}
  {{ user.short_name|title }} Approval
{% endblock %}

{% block content %}
  <h2>{{ user.full_name|title }}</h2>
  <form
    action="."
    method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        Approve Company
    </button>
  </form>
{% endblock %}

src/templates/user/base.html
{% extends base_template|default:"base.html" %}

src/templates/user/company_pending_approval.html
{% extends parent_template|default:"user/base.html" %}

{% block title %}
  {{ block.super }} - Pending Approval Company List
{% endblock %}

{% block content %}
  <h2>Pending Approval Company List</h2>
  <ul>
    {% for user in user_list %}
      <li>
        <a href="{{ user.get_absolute_url }}">
          {{ user.short_name|title }}</a> : {{ user.full_name }}
      </li>
    {% empty %}
      <li><em>There are currently no Companies pending approval.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

src/templates/user/form.html
{% extends parent_template|default:"user/base.html" %}

{% block title %}
    {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} User
{% endblock %}

{% block content %}
    <form
        action="."
        method="post"
    >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            {% if update %}Update{% else %}Create{% endif %} User
        </button>
    </form>
{% endblock %}

src/templates/user/list.html
{% extends parent_template|default:"user/base.html" %}

{% block title %}
  {{ block.super }} - User List
{% endblock %}
{% block content %}
  <h2>User List</h2>
  <ul>
    {% for user in user_list %}
      <li>
        <a href="{{ user.get_absolute_url }}">
          {{ user.short_name|title }}</a>
          {{user.verified}}
      </li>
    {% empty %}
      <li><em>There are currently no Users available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

src/templates/user/login.html
{% extends parent_template|default:'user/base.html' %}

{% block content %}
  <form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    {% if next %}
      <input
        type="hidden"
        name="next"
        value="{{ next }}">
    {% endif %}
    <button type="submit">Log In</button>
  </form>
  <ul>
    <li>
      <a href="{% url 'auth:password_reset' %}">
        Forgotten password?
      </a>
    </li>
  </ul>
{% endblock %}

src/templates/user/password_change_form.html
{% extends parent_template|default:'user/base.html' %}

{% block content %}
  <form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

src/templates/user/password_reset_confirm.html
{% extends "user/base.html" %}

{% block content %}
  {% if validlink %}
    <p>
      Please enter your new password twice so we can verify
      you typed it in correctly.
    </p>
    <form method="post" action=".">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change my password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because
      it has already been used. Please request a new
      password reset
      <a href="{% url 'auth:password_reset' %}">here</a>.
    </p>
  {% endif %}
{% endblock %}

src/templates/user/password_reset_form.html
{% extends parent_template|default:'user/base.html' %}

{% block content %}
  <form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}