src/config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from core.routers import urlpatterns as core_api_urls
from core.views import ListAllItems
from user.routers import urlpatterns as user_api_urls
from core.urls import urlpatterns as core_urls 
from user import urls as user_urls

api_urls = core_api_urls + user_api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include(api_urls)),
    path("", include(core_urls)),
    path(
        "", include((user_urls, "auth"), namespace="auth")
    ),
    path(
        "",
        ListAllItems.as_view(),
        name="site_root"
    ),
]

src/core/urls.py
from django.urls import path
from django.urls.base import reverse_lazy

from .views import(
    # CompanyDetail,
    # CompanyList,
    # CompanyCreate,
    # CompanyDelete,
    # CompanyUpdate,
    ItemDetail,
    ItemList,
    ItemCreate,
    ItemDelete,
    ItemUpdate,
    MoveItemToCart,
    CartDetail,
)

urlpatterns = [
    # path("company/", CompanyList.as_view(), name="company_list"),
    # path(
    #     "company/create/",
    #     CompanyCreate.as_view(),
    #     name="company_create"
    # ),
    # path(
    #     "company/<str:slug>/",
    #     CompanyDetail.as_view(),
    #     name="company_detail"
    # ),
    # path(
    #     "company/<str:slug>/update/",
    #     CompanyUpdate.as_view(),
    #     name="company_update"
    # ),
    # path(
    #     "company/<str:slug>/delete/",
    #     CompanyDelete.as_view(),
    #     name="company_delete"
    # ),
    path("item/", ItemList.as_view(), name="item_list"),
    path(
        "item/create/",
        ItemCreate.as_view(),
        name="item_create"
    ),
    path(
        "item/<str:slug>/",
        ItemDetail.as_view(),
        name="item_detail"
    ),
    path(
        "item/<str:slug>/update/",
        ItemUpdate.as_view(),
        name="item_update"
    ),
    path(
        "item/<str:slug>/delete/",
        ItemDelete.as_view(),
        name="item_delete"
    ),
    path("cart/", CartDetail.as_view(), name="cart"),
    path(
        "item/<str:slug>/move_to_cart/",
        MoveItemToCart.as_view(success_url=reverse_lazy("cart")),
        name="move_item_to_cart"
    ),
]

src/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse_lazy
from django.views.generic import TemplateView
from django_registration.backends.activation.views import (
    RegistrationView,
)

from .forms import CompanyRegistrationForm, RegistrationForm
from .views import (
    AccountPage,
    ActivationView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
    CompanyApprovalPendingList,
    CompanyApproveView,
    UserList,
)

urlpatterns = [
    path("account/", AccountPage.as_view(), name="account"),
    path(
        "login/",
        LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(
            template_name="user/logout.html"
        ),
        name="logout",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^activate/(?P<activation_key>[-:\w]+)/$",
        ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "register/",
        RegistrationView.as_view(
            form_class=RegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_complete"
            ),
        ),
        name="django_registration_register",
    ),
    path(
        "register/complete/",
        TemplateView.as_view(
            template_name="django_registration/registration_complete.html"
        ),
        name="django_registration_complete",
    ),
    path(
        "register/closed/",
        TemplateView.as_view(
            template_name="django_registration/registration_closed.html"
        ),
        name="django_registration_disallowed",
    ),
    path(
        "register_company/",
        RegistrationView.as_view(
            form_class=CompanyRegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_company_complete"
            ),
        ),
        name="django_registration_register_company",
    ),
    path(
        "register_company/complete/",
        TemplateView.as_view(
            template_name="django_registration/company_registration_complete.html"
        ),
        name="django_registration_company_complete",
    ),
    path(
        "companies_pending_approval/",
        CompanyApprovalPendingList.as_view(),
        name="django_approval_pending_companies",
    ),
    path(
        "approve_company/<int:pk>/",
        CompanyApproveView.as_view(),
        name="django_approve_company",
    ),
    path(
        "user/",
        UserList.as_view(),
        name="django_list_users"
    )
]

src/core/models.py
import uuid
from django.db import models
from django.db.models.deletion import CASCADE, DO_NOTHING
from django.db.models.fields import CharField, IntegerField
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse
from user.models import User, Address

DATETIME_FORMAT_STRING = "%A, %d %B %Y %I:%M%p"

# class Company(models.Model):
#     name = CharField(
#         max_length=48,
#         unique=True
#     )
#     slug = AutoSlugField(
#         max_length=20,
#         populate_from=["short_name"]
#     )
#     short_name = CharField(
#         max_length=20,
#         unique=True
#     )

#     class Meta:
#         ordering = ["name", "short_name"]

#     def __str__(self) -> str:
#         return f"{self.name} : {self.short_name}"

#     def get_absolute_url(self):
#         return reverse(
#             "company_detail",
#             kwargs={
#                 "slug" : self.slug
#             }
#         )


class Item(models.Model):
    name = models.CharField(
        max_length=63,
        db_index=True
    )
    slug = AutoSlugField(
        max_length=83,
        populate_from=["company__short_name","name"]
    )
    # images is an array of multiple image urls
    images = models.JSONField()
    """ 
    sizes = {
        {size} : {stock left}
        "M" : 20
    }
    """
    sizes = models.JSONField()
    # category
    company = models.ForeignKey(User, on_delete=CASCADE)
    # tags
    details = models.TextField(max_length=255)
    rating = models.FloatField()
    price = models.FloatField()
    discount = models.FloatField(default=0.0)
    
    class Meta:
        ordering = ["name"]
        unique_together = ("slug", "company")

    def __str__(self) -> str:
        return f"{self.company} : {self.name}"

    def get_absolute_url(self):
        return reverse(
            "item_detail", kwargs={"slug": self.slug}
        )
    
    def get_update_url(self):
        return reverse(
            "item_update", kwargs={"slug": self.slug}
        )
    
    def get_delete_url(self):
        return reverse(
            "item_delete", kwargs={"slug": self.slug}
        )
    
    def add_to_cart_url(self):
        return reverse(
            "move_item_to_cart", kwargs={"slug": self.slug}
        )


# class MyUser(models.Model):
#     uid = models.UUIDField(
#         default=uuid.uuid4,
#         unique=True,
#         editable=False
#     )
#     password = models.CharField(max_length=24)
#     name = models.CharField(max_length=48)
#     email = models.EmailField(unique=True)
#     phone = models.CharField(unique=True, max_length=16)
#     gender = models.CharField(max_length=10)

#     class Meta:
#         ordering = ["name"]

#     def __str__(self) -> str:
#         return f"{self.name}: {self.email}"
    
#     def get_absolute_url(self):
#         return reverse(
#             "user_detail",
#             kwargs={
#                 "uid" : self.uid
#             }
#         )


# class Address(models.Model):
#     user = models.ForeignKey(MyUser,on_delete=CASCADE)
#     short_name = models.CharField(max_length=20)
#     slug = AutoSlugField(
#         max_length=90,
#         populate_from=["user__uid","short_name"]
#     )
#     line_1 = models.CharField(max_length=32)
#     line_2 = models.CharField(max_length=32)
#     city = models.CharField(max_length=32)
#     state = models.CharField(max_length=32)
#     pincode = models.IntegerField()
#     country = models.CharField(max_length=32)

#     class Meta:
#         ordering = ["user", "state", "city"]
#         unique_together = ("user", "line_1", "line_2", "city", "state", "pincode", "country")
#         unique_together = ("user", "short_name")
#     def __str__(self) -> str:
#         return f"{self.user}: , {self.line_1} {self.line_2} {self.city} {self.state} {self.pincode}"



class Order(models.Model):
    order_timestamp = models.DateTimeField()
    oid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False
    )
    user = models.ForeignKey(User, on_delete=DO_NOTHING)
    amount = models.FloatField()
    discount = models.FloatField(default=0.0)
    address = models.ForeignKey(Address, on_delete=DO_NOTHING)

    class Meta:
        get_latest_by = "order_timestamp"
        ordering = ["order_timestamp"]

    def __str__(self) -> str:
        date_time_string = self.order_timestamp.strftime(DATETIME_FORMAT_STRING)
        return f"{self.user}: {date_time_string}"



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    item = models.ForeignKey(Item, on_delete=CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=10)


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=DO_NOTHING)
    slug = AutoSlugField(
        max_length=83,
        populate_from=["order__oid","item__id"]
    )
    order = models.ForeignKey(Order, on_delete=CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    discount = models.FloatField(default=0.0)
    delivery_timestamp = models.DateTimeField()
    payment_timestamp = models.DateTimeField()
    payment_type = models.CharField(max_length=20)

    class Meta:
        get_latest_by = "delivery_timestamp"
        ordering = ["order", "item"]


    def __str__(self) -> str:
        return f"{self.order}: {self.item}"


class Review(models.Model):
    item = models.ForeignKey(Item, on_delete=CASCADE)
    slug = AutoSlugField(
        max_length=83,
        populate_from=["order__oid","item__id"]
    )
    order = models.ForeignKey(Order, on_delete=CASCADE)
    timestamp = models.DateTimeField()
    images = models.JSONField()
    rating = IntegerField()
    description = models.TextField()

    class Meta:
        get_latest_by = "timestamp"
        ordering = ["item", "rating"]

    def __str__(self) -> str:
        return f"{self.order_id}: {self.item_id}"

src/user/models.py
import uuid
from django.db.models.deletion import CASCADE
from django.urls import reverse
from improved_user.model_mixins import AbstractUser
from django.db import models
from django_extensions.db.fields import AutoSlugField

class User(AbstractUser):

    type = models.CharField(
        max_length=20,
        default="buyer"
    )
    verified = models.BooleanField(default=True)
    uid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
    )

    def __str__(self):
        return f"email: {self.email}, type: {self.type}"

    def get_absolute_url(self):
        return reverse(
            "auth:django_approve_company",
            kwargs={
                "pk": self.pk
            }
        )


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    short_name = models.CharField(max_length=20)
    slug = AutoSlugField(
        max_length=90,
        populate_from=["user__uid","short_name"]
    )
    line_1 = models.CharField(max_length=32)
    line_2 = models.CharField(max_length=32)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=32)
    pincode = models.IntegerField()
    country = models.CharField(max_length=32)

src/templates/base.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Core{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css"
      href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" type="text/css"
      href="{% static 'css/skeleton.css' %}">
    <link rel="stylesheet" type="text/css"
      href="{% static 'css/style.css' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <div class="container">
      <!--[if lte IE 9]>
        <div class="row">
          <p class="browserupgrade">
            You are using an <strong>outdated</strong> browser. Please
            <a href="https://browsehappy.com/">upgrade your browser</a>
            to improve your experience and security.
          </p>
        </div>
      <![endif]-->

      {% if messages %}
      <div class="row">
        <div class="twelve columns">
          <ul class="messages">
            {% for message in messages %}
              {% if message.tags %}
                <li class="{{ message.tags }}">
              {% else %}
                <li>
              {% endif %}
              {{ message }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      {% endif %}

      <div class="status row">
        <div class="offset-by-eight four columns">
          <ul class="inline">
            {% if user.is_authenticated %}
            <li><a href="{% url 'auth:account' %}">
              Manage Account</a></li>
            <li><a href="{% url 'auth:logout' %}">
              Log Out</a></li>
            {% else %}
            <li><a href="{% url 'auth:django_registration_register' %}">
              Register
            </a></li>
            <li><a href="{% url 'auth:login' %}?next={{ request.path }}">
              Log In</a></li>
            {% endif %}
            <li><a href="{% url 'cart' %}">
              Cart
            </a></li>
          </ul>
        </div><!-- four columns -->
      </div><!-- status row -->

      <header class="row">
        <div class="offset-by-one ten columns">
          <h1 class="logo"><a href="{% url 'site_root' %}" style="text-decoration:none;">JAJIO</a></h1>
        </div>
      </header>

      <nav>
        <ul>
          <li><a href="{% url 'api-root' %}">Explore Our Api</a></li>
          {% if perms.core.add_item %}
            <li><a href="{% url 'item_list' %}">Item</a></li>
          {% endif%}
          {% if perms.user.add_user %}
            <li><a href="{% url 'auth:django_approval_pending_companies' %}">Approve Companies</a></li>
          {% endif %}
        </ul>
      </nav>
      
      <main>
        {% block content %}{% endblock %}
      </main>

    </div><!-- container-->

    <footer>
      <p>
        Built by Nupur Brahmanya under the
        <a href="https://opensource.org/licenses/BSD-2-Clause">
          Simplified BSD License</a>.
      </p>
    <footer>

  </body>
</html>

src/templates/root.html
{% extends base_template|default:"base.html" %}

{% block content %}
  <p>
    Welcome to Jajio, the site built for E-commerce class project.
    Please use the navigation links above to roam
    the site.
  </p>
  <ul>
    {% for item in item_list %}
      <li>
        <a href="{{ item.get_absolute_url }}">
          {{ item.name|title }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no Items available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}