src/config/urls.py
"""config URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from core.routers import urlpatterns as core_api_urls
from core.views import ListAllItems
from user.routers import urlpatterns as user_api_urls
from core.urls import urlpatterns as core_urls 
from user import urls as user_urls

api_urls = core_api_urls + user_api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include(api_urls)),
    path("", include(core_urls)),
    path(
        "", include((user_urls, "auth"), namespace="auth")
    ),
    path(
        "",
        ListAllItems.as_view(),
        name="site_root"
    ),
]

src/core/urls.py
from django.urls import path
from django.urls.base import reverse_lazy

from .views import(
    # CompanyDetail,
    # CompanyList,
    # CompanyCreate,
    # CompanyDelete,
    # CompanyUpdate,
    ItemDetail,
    ItemList,
    ItemCreate,
    ItemDelete,
    ItemUpdate,
    MoveItemToCart,
    CartDetail,
)

urlpatterns = [
    # path("company/", CompanyList.as_view(), name="company_list"),
    # path(
    #     "company/create/",
    #     CompanyCreate.as_view(),
    #     name="company_create"
    # ),
    # path(
    #     "company/<str:slug>/",
    #     CompanyDetail.as_view(),
    #     name="company_detail"
    # ),
    # path(
    #     "company/<str:slug>/update/",
    #     CompanyUpdate.as_view(),
    #     name="company_update"
    # ),
    # path(
    #     "company/<str:slug>/delete/",
    #     CompanyDelete.as_view(),
    #     name="company_delete"
    # ),
    path("item/", ItemList.as_view(), name="item_list"),
    path(
        "item/create/",
        ItemCreate.as_view(),
        name="item_create"
    ),
    path(
        "item/<str:slug>/",
        ItemDetail.as_view(),
        name="item_detail"
    ),
    path(
        "item/<str:slug>/update/",
        ItemUpdate.as_view(),
        name="item_update"
    ),
    path(
        "item/<str:slug>/delete/",
        ItemDelete.as_view(),
        name="item_delete"
    ),
    path("cart/", CartDetail.as_view(), name="cart"),
    path(
        "item/<str:slug>/move_to_cart/",
        MoveItemToCart.as_view(success_url=reverse_lazy("cart")),
        name="move_item_to_cart"
    ),
]

src/user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse_lazy
from django.views.generic import TemplateView
from django_registration.backends.activation.views import (
    RegistrationView,
)

from .forms import CompanyRegistrationForm, RegistrationForm
from .views import (
    AccountPage,
    ActivationView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
    CompanyApprovalPendingList,
    CompanyApproveView,
    UserList,
)

urlpatterns = [
    path("account/", AccountPage.as_view(), name="account"),
    path(
        "login/",
        LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(
            template_name="user/logout.html"
        ),
        name="logout",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^activate/(?P<activation_key>[-:\w]+)/$",
        ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "register/",
        RegistrationView.as_view(
            form_class=RegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_complete"
            ),
        ),
        name="django_registration_register",
    ),
    path(
        "register/complete/",
        TemplateView.as_view(
            template_name="django_registration/registration_complete.html"
        ),
        name="django_registration_complete",
    ),
    path(
        "register/closed/",
        TemplateView.as_view(
            template_name="django_registration/registration_closed.html"
        ),
        name="django_registration_disallowed",
    ),
    path(
        "register_company/",
        RegistrationView.as_view(
            form_class=CompanyRegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_company_complete"
            ),
        ),
        name="django_registration_register_company",
    ),
    path(
        "register_company/complete/",
        TemplateView.as_view(
            template_name="django_registration/company_registration_complete.html"
        ),
        name="django_registration_company_complete",
    ),
    path(
        "companies_pending_approval/",
        CompanyApprovalPendingList.as_view(),
        name="django_approval_pending_companies",
    ),
    path(
        "approve_company/<int:pk>/",
        CompanyApproveView.as_view(),
        name="django_approve_company",
    ),
    path(
        "user/",
        UserList.as_view(),
        name="django_list_users"
    )
]

src/templates/django_registration/activation_failed.html
{% extends parent_template|default:'django_registration/base.html' %}

{% block title %}
{{ block.super }} - Account Activation Failed
{% endblock %}

{% block content %}
  <div>
    <p>This activation link is either longer valid 
      if you registered more than 7 days ago
      or your credentials have not been verfied 
      by our administrator.
    </p>
  </div>
{% endblock %}

src/templates/django_registration/base.html
{% extends base_template|default:'base.html' %}

src/templates/django_registration/company_registration_complete.html
{% extends parent_template|default:'django_registration/base.html' %}

{% block title %}
{{ block.super }} - Account Created
{% endblock %}

{% block content %}
  <div>
    <p>Your account has been created!</p>
    <p>Please check your email for
      the activation link which will 
      be active once we have verified your credentials.</p>
    <p>You are free to close this window.</p>
  </div>
{% endblock %}

src/templates/django_registration/registration_complete.html
{% extends parent_template|default:'django_registration/base.html' %}

{% block title %}
{{ block.super }} - Account Created
{% endblock %}

{% block content %}
  <div>
    <p>Your account has been created!</p>
    <p>Please check your email for
      the activation link.</p>
    <p>You are free to close this window.</p>
  </div>
{% endblock %}

src/templates/django_registration/registration_form.html
{% extends parent_template|default:'django_registration/base.html' %}

{% block title %}
{{ block.super }} - Create Account
{% endblock %}

{% block content %}
  <form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
  <ul>
    <li>
      <a href="{% url 'auth:login' %}">
        Already have an account?
      </a>
    </li>
    {% url 'auth:django_registration_register' as comparision_url %}
    {% if request.get_full_path == comparision_url %}
      <li>
        <a href="{% url 'auth:django_registration_register_company' %}">
          Register as company
        </a>
      </li>
    {% else %}
    <li>
      <a href="{% url 'auth:django_registration_register' %}">
        Register as user
      </a>
    </li>
    {% endif %}
  </ul>
{% endblock %}